USE [COREAPP2]
GO
/****** Object:  Table [dbo].[T_COMMON_CODE]    Script Date: 2018-12-15 오후 2:01:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_COMMON_CODE](
	[CODE_TYPE] [nvarchar](32) NOT NULL,
	[CODE_TYPE_NAME] [nvarchar](128) NOT NULL,
	[CODE_ID] [nvarchar](32) NOT NULL,
	[CODE_NAME] [nvarchar](128) NOT NULL,
	[CODE_VAL] [int] NULL,
	[SORT_ORDER] [int] NULL,
	[USE_YN] [bit] NULL,
	[CODE_COMMENT] [nvarchar](128) NULL,
	[CREATE_USER_ID] [nvarchar](16) NULL,
	[CREATE_DT] [datetime] NULL,
 CONSTRAINT [PK_T_COMMON_CODE] PRIMARY KEY CLUSTERED 
(
	[CODE_TYPE] ASC,
	[CODE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_MENU_MASTER]    Script Date: 2018-12-15 오후 2:01:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_MENU_MASTER](
	[MENU_IDENTITY] [int] IDENTITY(1,1) NOT NULL,
	[MENU_ID] [nvarchar](64) NULL,
	[MENU_NAME] [nvarchar](64) NULL,
	[PARENT_MENUID] [nvarchar](64) NULL,
	[USER_ROLL] [nvarchar](450) NULL,
	[USER_AUTH] [int] NULL,
	[USER_DUTY] [int] NULL,
	[MENU_AREA] [nvarchar](64) NULL,
	[MENU_CONTROLLER] [nvarchar](64) NULL,
	[MENU_ACTION] [nvarchar](64) NULL,
	[USE_YN] [bit] NULL,
	[SORT_ORDER] [int] NOT NULL,
	[CREATED_DATE] [datetime] NULL,
	[CSS_CLASS] [nvarchar](64) NULL,
 CONSTRAINT [PK_T_MENU_MASTER] PRIMARY KEY CLUSTERED 
(
	[MENU_IDENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [COREAPP2]
GO
/****** Object:  Table [dbo].[T_COMP_INFO]    Script Date: 2018-12-15 오후 8:07:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_COMP_INFO](
	[COMP_SEQ] [bigint] IDENTITY(1,1) NOT NULL,
	[COMP_NAME] [nvarchar](128) NOT NULL,
	[COMP_DESCRIPTION] [nvarchar](1024) NULL,
	[COMP_REF] [nvarchar](256) NULL,
	[STANDARD_YEAR] [nvarchar](4) NULL,
	[DIAG_TYPE] [nvarchar](32) NOT NULL,
	[CONFIRM_YN] [bit] NULL,
	[USE_YN] [bit] NULL,
	[CREATE_USER_ID] [nvarchar](16) NULL,
	[CREATE_DT] [datetime] NULL,
	[UPDATE_USER_ID] [nvarchar](16) NULL,
	[UPDATE_DT] [datetime] NULL,
	[COMP_DETAIL_GUBUN] [nvarchar](32) NULL,
 CONSTRAINT [PK_T_COMP_INFO] PRIMARY KEY CLUSTERED 
(
	[COMP_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_COMP_INFO] ADD  DEFAULT ('') FOR [COMP_DETAIL_GUBUN]
GO

/****** Object:  Table [dbo].[T_VULN_GROUP]    Script Date: 2018-12-15 오후 8:07:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_VULN_GROUP](
	[GROUP_SEQ] [bigint] NOT NULL,
	[UPPER_SEQ] [bigint] NOT NULL,
	[LEVEL] [int] NOT NULL,
	[GROUP_TYPE] [nvarchar](32) NOT NULL,
	[COMP_SEQ] [bigint] NOT NULL,
	[DIAG_KIND] [nvarchar](32) NULL,
	[DIAG_TERM] [nvarchar](32) NULL,
	[GROUP_ID] [nvarchar](32) NULL,
	[GROUP_NAME] [nvarchar](128) NULL,
	[DIAG_TOOL] [nvarchar](32) NULL,
	[SORT_ORDER] [int] NULL,
	[CREATE_USER_ID] [nvarchar](16) NULL,
	[CREATE_DT] [datetime] NULL,
	[UPDATE_USER_ID] [nvarchar](16) NULL,
	[UPDATE_DT] [datetime] NULL,
 CONSTRAINT [PK_T_VULN_GROUP] PRIMARY KEY CLUSTERED 
(
	[GROUP_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[T_VULN_GROUP]  WITH CHECK ADD FOREIGN KEY([COMP_SEQ])
REFERENCES [dbo].[T_COMP_INFO] ([COMP_SEQ])
GO

/****** Object:  Table [dbo].[T_VULN]    Script Date: 2018-12-15 오후 8:07:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_VULN](
	[VULN_SEQ] [bigint] IDENTITY(1,1) NOT NULL,
	[GROUP_SEQ] [bigint] NOT NULL,
	[MANUAL_YN] [bit] NULL,
	[AUTO_YN] [bit] NULL,
	[MANAGE_ID] [nvarchar](32) NULL,
	[CLIENT_STANDARD_ID] [nvarchar](32) NULL,
	[VULN_NAME] [nvarchar](128) NULL,
	[SORT_ORDER] [int] NULL,
	[RULE_YN] [bit] NULL,
	[RATE] [int] NULL,
	[SCORE] [int] NULL,
	[APPLY_TIME] [nvarchar](2) NULL,
	[DETAIL] [text] NULL,
	[DETAIL_PATH] [nvarchar](256) NULL,
	[JUDGEMENT] [nvarchar](2048) NULL,
	[EFFECT] [nvarchar](2048) NULL,
	[REMEDY] [text] NULL,
	[REMEDY_PATH] [nvarchar](256) NULL,
	[REFRRENCE] [nvarchar](2048) NULL,
	[PARSER_CONTENTS] [text] NULL,
	[ORG_PARSER_CONTENTS] [text] NULL,
	[APPLY_TARGET] [nvarchar](1024) NULL,
	[USE_YN] [bit] NULL,
	[EXCEPT_CD] [nvarchar](2) NULL,
	[EXCEPT_TERM_TYPE] [nvarchar](2) NULL,
	[EXCEPT_TERM_FR] [datetime] NULL,
	[EXCEPT_TERM_TO] [datetime] NULL,
	[EXCEPT_REASON] [nvarchar](1024) NULL,
	[EXCEPT_USER_ID] [nvarchar](16) NULL,
	[EXCEPT_DT] [datetime] NULL,
	[CREATE_USER_ID] [nvarchar](16) NULL,
	[CREATE_DT] [datetime] NULL,
	[UPDATE_USER_ID] [nvarchar](16) NULL,
	[UPDATE_DT] [datetime] NULL,
	[VULGROUP] [bigint] NULL,
	[VULNO] [nvarchar](32) NULL,
	[REMEDY_DETAIL] [text] NULL,
	[OVERVIEW] [nvarchar](max) NULL,
	[MANAGEMENT_VULN_YN] [bit] NULL,
 CONSTRAINT [PK_T_VULN] PRIMARY KEY CLUSTERED 
(
	[VULN_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[T_VULN] ADD  DEFAULT ((0)) FOR [VULGROUP]
GO
ALTER TABLE [dbo].[T_VULN] ADD  DEFAULT ('') FOR [VULNO]
GO
ALTER TABLE [dbo].[T_VULN] ADD  DEFAULT (NULL) FOR [MANAGEMENT_VULN_YN]
GO
ALTER TABLE [dbo].[T_VULN]  WITH CHECK ADD FOREIGN KEY([GROUP_SEQ])
REFERENCES [dbo].[T_VULN_GROUP] ([GROUP_SEQ])
GO