// <auto-generated />
using System;
using COREAPP2.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace COREAPP2.Persistence.DbContexts.Migrations
{
    [DbContext(typeof(SpDbContext))]
    partial class SpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("COREAPP2.Domain.Entities.SpModel.T_COMP_INFO", b =>
                {
                    b.Property<long>("COMP_SEQ")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COMP_DESCRIPTION");

                    b.Property<string>("COMP_DETAIL_GUBUN");

                    b.Property<string>("COMP_NAME");

                    b.Property<string>("COMP_REF");

                    b.Property<bool?>("CONFIRM_YN");

                    b.Property<DateTime?>("CREATE_DT");

                    b.Property<string>("CREATE_USER_ID");

                    b.Property<string>("DIAG_TYPE");

                    b.Property<string>("STANDARD_YEAR");

                    b.Property<DateTime?>("UPDATE_DT");

                    b.Property<string>("UPDATE_USER_ID");

                    b.Property<bool?>("USE_YN");

                    b.HasKey("COMP_SEQ");

                    b.ToTable("T_COMP_INFO");
                });

            modelBuilder.Entity("COREAPP2.Domain.Entities.SpModel.T_VULN", b =>
                {
                    b.Property<long>("VULN_SEQ")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APPLY_TARGET");

                    b.Property<string>("APPLY_TIME");

                    b.Property<bool?>("AUTO_YN");

                    b.Property<string>("CLIENT_STANDARD_ID");

                    b.Property<DateTime?>("CREATE_DT");

                    b.Property<string>("CREATE_USER_ID");

                    b.Property<string>("DETAIL");

                    b.Property<string>("DETAIL_PATH");

                    b.Property<string>("EFFECT");

                    b.Property<string>("EXCEPT_CD");

                    b.Property<DateTime?>("EXCEPT_DT");

                    b.Property<string>("EXCEPT_REASON");

                    b.Property<DateTime?>("EXCEPT_TERM_FR");

                    b.Property<DateTime?>("EXCEPT_TERM_TO");

                    b.Property<string>("EXCEPT_TERM_TYPE");

                    b.Property<string>("EXCEPT_USER_ID");

                    b.Property<long>("GROUP_SEQ");

                    b.Property<string>("JUDGEMENT");

                    b.Property<bool?>("MANAGEMENT_VULN_YN");

                    b.Property<string>("MANAGE_ID");

                    b.Property<bool?>("MANUAL_YN");

                    b.Property<string>("ORG_PARSER_CONTENTS");

                    b.Property<string>("OVERVIEW");

                    b.Property<string>("PARSER_CONTENTS");

                    b.Property<int?>("RATE");

                    b.Property<string>("REFRRENCE");

                    b.Property<string>("REMEDY");

                    b.Property<string>("REMEDY_DETAIL");

                    b.Property<string>("REMEDY_PATH");

                    b.Property<bool?>("RULE_YN");

                    b.Property<int?>("SCORE");

                    b.Property<int?>("SORT_ORDER");

                    b.Property<DateTime?>("UPDATE_DT");

                    b.Property<string>("UPDATE_USER_ID");

                    b.Property<bool?>("USE_YN");

                    b.Property<long?>("VULGROUP");

                    b.Property<string>("VULNO");

                    b.Property<string>("VULN_NAME");

                    b.HasKey("VULN_SEQ");

                    b.HasIndex("GROUP_SEQ");

                    b.ToTable("T_VULN");
                });

            modelBuilder.Entity("COREAPP2.Domain.Entities.SpModel.T_VULN_GROUP", b =>
                {
                    b.Property<long>("GROUP_SEQ")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("COMP_SEQ");

                    b.Property<DateTime?>("CREATE_DT");

                    b.Property<string>("CREATE_USER_ID");

                    b.Property<string>("DIAG_KIND");

                    b.Property<string>("DIAG_TERM");

                    b.Property<string>("DIAG_TOOL");

                    b.Property<string>("GROUP_ID");

                    b.Property<string>("GROUP_NAME");

                    b.Property<string>("GROUP_TYPE");

                    b.Property<int>("LEVEL");

                    b.Property<int?>("SORT_ORDER");

                    b.Property<DateTime?>("UPDATE_DT");

                    b.Property<string>("UPDATE_USER_ID");

                    b.Property<long>("UPPER_SEQ");

                    b.HasKey("GROUP_SEQ");

                    b.HasIndex("COMP_SEQ");

                    b.ToTable("T_VULN_GROUP");
                });

            modelBuilder.Entity("COREAPP2.Domain.Entities.SpModel.T_VULN", b =>
                {
                    b.HasOne("COREAPP2.Domain.Entities.SpModel.T_VULN_GROUP", "GROUP_SEQNavigation")
                        .WithMany("T_VULN")
                        .HasForeignKey("GROUP_SEQ")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("COREAPP2.Domain.Entities.SpModel.T_VULN_GROUP", b =>
                {
                    b.HasOne("COREAPP2.Domain.Entities.SpModel.T_COMP_INFO", "COMP_SEQNavigation")
                        .WithMany("T_VULN_GROUP")
                        .HasForeignKey("COMP_SEQ")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
